language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"

install:
  - composer update --dev --prefer-source --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text
