#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

error_reporting(-1);
ini_set('display_errors', 1);

try {
    $compiler = new Pure\Utils\Compiler();
    $compiler->compile(__DIR__ . '/', 'pure.phar');
} catch (\Exception $e) {
    echo 'Failed to compile phar:' . $e->getMessage() . ' at ' . $e->getFile() . ':' . $e->getLine();
    exit(1);
}