#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

$pharName = 'pure.phar';
$pharFile = __DIR__ . '/' . $pharName;

if (file_exists($pharFile)) {
    unlink($pharFile);
}

$phar = new \Phar($pharFile, 0, $pharName);
$phar->setSignatureAlgorithm(\Phar::SHA1);

$phar->startBuffering();

$finder = new Symfony\Component\Finder\Finder();
$finder->files()
    ->ignoreVCS(true)
    ->name('*.php')
    ->name('pure')
    ->exclude('phpunit')
    ->exclude('Tests')
    ->exclude('test')
    ->exclude('tests')
    ->exclude('bin')
    ->in(__DIR__);

foreach ($finder as $fileInfo) {
    $file = str_replace(__DIR__, '', $fileInfo->getRealPath());

    echo "Add file: " . $file . "\n";

    $phar->addFile($fileInfo->getRealPath(), $file);
}

$stub = <<<'STUB'
#!/usr/bin/env php
<?php
Phar::mapPhar('pure.phar');
require 'phar://pure.phar/pure';
__HALT_COMPILER();
STUB;

$phar->setStub($stub);

$phar->stopBuffering();

unset($phar);